version: '3.9'

services:
  backend:
    image: ghcr.io/blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "echo 'Attempting to create and set permissions for /app/dets' && mkdir -p /app/dets && chmod -R 777 /app/dets && echo 'Listing /app:' && ls -la /app && echo 'Listing /app/dets:' && ls -la /app/dets && echo 'Current PWD:' && pwd && echo 'Current user ID:' && id && echo 'Starting Blockscout...' && bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/
      # - blockscout_dets_data:/app/dets/ # Comentado para prueba
